### ISSUE TITLE
Negative pupil range in extractPupilPerimeter.m

### ISSUE THREAD

**Issue by gfrazzetta** [gkaguirrelab/LiveTrackAnalysisToolbox#21]
The 50% pupilRange increase can result in a negative pupil range when pupilRange(1)>pupilRange(2). This happened for TOME_3020 s2 run n.8 (when ordered by name) and TOME_3014 s1 run n.1 (when ordered by name).

Problematic lines:
https://github.com/gkaguirrelab/LiveTrackAnalysisToolbox/blob/master/code/processVideos/extractPupilPerimeter.m#L181

**Comment by gkaguirre** [comment]
I changed the check for boundary conditions and confirmed that this runs without crashing on TOME_3014 s1, run 1, as well as on TOME_3020, S2, run 1
