### ISSUE TITLE
controlFile is appended instead of over-written

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/LiveTrackAnalysisToolbox#28]
When called with the `overwriteControlFile` flag, the makePrelimControlFile routine should completely over-write any existing control file. Instead, the newly calculated instructions are appended to the existing control file.

**Comment by gfrazzetta** [comment]
Fixed with [this commit](https://github.com/gkaguirrelab/LiveTrackAnalysisToolbox/commit/f9e9de4d1555b4cac20c3aee4ac4bc924866dcbc)
